// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFnNdBuepxbQBgzi3HwQHiBhk9khew8IE',
    appId: '1:67159247551:web:e807115d55c61fc59f540a',
    messagingSenderId: '67159247551',
    projectId: 'pickafrika-24713',
    authDomain: 'pickafrika-24713.firebaseapp.com',
    storageBucket: 'pickafrika-24713.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWcXooggTpJRTMzb1b55kOmYf5aL7-s48',
    appId: '1:67159247551:android:555bbd5bf1ff94a99f540a',
    messagingSenderId: '67159247551',
    projectId: 'pickafrika-24713',
    storageBucket: 'pickafrika-24713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClLtBaNC7bhXbTaLjqP3xmTAQYlQl9aAk',
    appId: '1:67159247551:ios:ae9a0bd8dedc80ac9f540a',
    messagingSenderId: '67159247551',
    projectId: 'pickafrika-24713',
    storageBucket: 'pickafrika-24713.appspot.com',
    androidClientId: '67159247551-ktgha7dm34ur34kbv9d6f0ga4beinpc0.apps.googleusercontent.com',
    iosClientId: '67159247551-qk8eol621iph7i416hm3fkvtimhvq0cm.apps.googleusercontent.com',
    iosBundleId: 'com.example.pickafrika',
  );
}
